# Generated by Django 4.1.4 on 2023-04-20 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0004_remove_student_tb_average'),
    ]

    operations = [
        migrations.CreateModel(
            name='average_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.CharField(max_length=20)),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.student_tb')),
            ],
        ),
    ]
