# Generated by Django 4.1.4 on 2023-04-21 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0005_average_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=20)),
                ('date_of_birth', models.CharField(max_length=20)),
                ('mark_of_physics', models.IntegerField()),
                ('mark_of_maths', models.IntegerField()),
                ('mark_of_chemistry', models.IntegerField()),
                ('mark_of_computerscience', models.IntegerField()),
                ('percentage', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='average_tb',
            name='studentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.student_table'),
        ),
        migrations.DeleteModel(
            name='student_tb',
        ),
    ]
