# Generated by Django 4.1.4 on 2023-04-21 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0006_student_table_alter_average_tb_studentid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='average_tb',
        ),
    ]
